language: php
dist: trusty
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=phpcs.xml src

after_script:
  - php vendor/bin/coveralls -v
